[buildPlans.iosevka-custom]
family = "Iosevka Custom"
spacing = "fontconfig-mono"
serifs = "sans"
no-cv-ss = false

[buildPlans.iosevka-custom.variants.design]
i = "serifed"
l = "flat-tailed"
t = "flat-hook"
y = "straight-turn"
brace = "straight"
percent = "rings-continuous-slash"

  [buildPlans.iosevka-custom.ligations]
  inherits = "php"
