# NF: --complete --makegroups --careful

[buildPlans.iosevka-custom]
family = "Iosevka Custom"
spacing = "normal"
serifs = "sans"
no-cv-ss = true
export-glyph-names = false

  [buildPlans.iosevka-custom.variants]
  inherits = "ss14"

    [buildPlans.iosevka-custom.variants.design]
    capital-a = "straight-serifless"
    capital-b = "standard-serifless"
    capital-c = "serifless"
    capital-d = "standard-serifless"
    capital-e = "serifless"
    capital-f = "serifless"
    capital-g = "toothless-rounded-serifless-hooked"
    capital-h = "serifless"
    capital-i = "short-serifed"
    capital-j = "serifless"
    capital-k = "symmetric-connected-serifless"
    capital-l = "serifless"
    capital-m = "flat-bottom"
    capital-n = "standard"
    capital-p = "closed"
    capital-q = "straight"
    capital-r = "straight"
    capital-s = "serifless"
    capital-t = "serifless"
    capital-u = "toothless-rounded"
    capital-v = "straight"
    capital-w = "straight-flat-top"
    capital-x = "straight-serifless"
    capital-y = "straight-serifless"
    capital-z = "straight-serifless"
    a = "double-storey-serifless"
    b = "toothed"
    c = "serifless"
    d = "toothed-serifless"
    e = "flat-crossbar"
    f = "serifless"
    g = "single-storey-serifless"
    h = "straight"
    i = "flat-tailed"
    j = "serifless"
    k = "symmetric-connected-serifless"
    l = "flat-tailed"
    m = "normal"
    n = "straight"
    p = "eared"
    q = "straight"
    r = "serifless"
    s = "serifless"
    t = "flat-hook"
    u = "toothed"
    v = "straight"
    w = "straight-flat-top"
    x = "straight-serifless"
    y = "straight"
    z = "straight-serifless"
    long-s = "flat-hook"
    eszet = "sulzbacher"
    turn-v = "straight"
    lower-alpha = "crossing"
    lower-delta = "flat-top"
    capital-gamma = "serifless"
    lower-iota = "serifed-flat-tailed"
    lower-lambda = "straight"
    lower-mu = "tailed"
    lower-xi = "rounded"
    cyrl-capital-zhe = "symmetric-connected"
    cyrl-zhe = "symmetric-connected"
    cyrl-capital-ze = "serifless"
    cyrl-ze = "serifless"
    cyrl-capital-ka = "symmetric-connected-serifless"
    cyrl-ka = "symmetric-connected-serifless"
    cyrl-el = "straight"
    cyrl-en = "serifless"
    cyrl-ef = "serifless"
    cyrl-che = "standard"
    cyrl-capital-u = "straight"
    cyrl-capital-ya = "straight"
    cyrl-ya = "straight"
    cyrl-yeri = "corner"
    cyrl-yery = "corner"
    zero = "slashed"
    one = "no-base"
    two = "straight-neck"
    three = "flat-top"
    four = "semi-open-non-crossing"
    five = "vertical-upper-left-bar"
    six = "straight-bar"
    seven = "straight-serifless"
    eight = "crossing-asymmetric"
    nine = "straight-bar"
    diacritic-dot = "round"
    punctuation-dot = "round"
    tilde = "low"
    asterisk = "turn-hex-low"
    underscore = "high"
    caret = "medium"
    paren = "normal"
    brace = "straight"
    ampersand = "upper-open"
    at = "threefold"
    dollar = "through"
    percent = "rings-continuous-slash"
    bar = "natural-slope"
    ascii-single-quote = "straight"
    ascii-grave = "straight"
    question = "smooth"
    pilcrow = "low"
    cent = "through"
    partial-derivative = "straight-bar"
    micro-sign = "tailless"
    lig-ltgteq = "slanted"
    lig-neq = "more-slanted"
    lig-equal-chain = "with-notch"
    lig-hyphen-chain = "without-notch"
    lig-double-arrow-bar = "with-notch"
    lig-single-arrow-bar = "with-notch"

  [buildPlans.iosevka-custom.ligations]
  inherits = "haskell"

