[buildPlans.iosevka-custom]
family = "Iosevka Custom"
serifs = "sans"
spacing = "fontconfig-mono"
noCvSs = false
exportGlyphNames = false

  [buildPlans.iosevka-custom.variants]
  inherits = "ss14"

    [buildPlans.iosevka-custom.variants.design]
    capital-i = "short-serifed"
    capital-j = "serifless"
    capital-w = "straight-flat-top-serifless"
    f = "serifless"
    g = "single-storey-serifless"
    i = "flat-tailed"
    j = "serifless"
    k = "symmetric-connected-serifless"
    l = "flat-tailed"
    n = "straight-serifless"
    t = "flat-hook-short-neck2"
    u = "toothed-serifless"
    cyrl-capital-zhe = "symmetric-connected"
    zero = "unslashed"
    one = "no-base"
    five = "upright-arched-serifless"
    seven = "straight-serifless"
    eight = "two-circles"
    tilde = "low"
    asterisk = "hex-low"
    underscore = "high"
    caret = "medium"
    paren = "normal"
    brace = "straight"
    at = "threefold"
    bar = "natural-slope"
    ascii-grave = "straight"
    question = "smooth"
    lig-ltgteq = "flat"
    lig-neq = "slightly-slanted"
    lig-equal-chain = "with-notch"
    lig-hyphen-chain = "with-notch"
    lig-double-arrow-bar = "with-notch"
    lig-single-arrow-bar = "with-notch"

  [buildPlans.iosevka-custom.ligations]
  inherits = "haskell"

